GET http://localhost:3333/test

###
POST http://localhost:3333/api/auth/signup
Content-Type: application/json

{
    "username": "Pecko",
    "email": "pecko@gmail.com",
    "password": "pecko"
}

###
POST http://localhost:3333/api/auth/login
Content-Type: application/json

{
    "username": "Pecko",
    "email": "pecko@gmail.com",
    "password": "pecko"
}